//! Ownership tracking.
//!
//! cpx must never clobber a file a human wrote. A comment marker identifies
//! generated shell scripts, but JSON cannot carry one, so ownership is
//! recorded in a state manifest at `<root>/state.json`: every artifact cpx
//! writes, with the SHA-256 of what it wrote. An artifact whose content no
//! longer matches its recorded hash was edited by hand and is treated as
//! foreign, so a hand-edit is backed up rather than silently overwritten.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::io;
use std::path::{Path, PathBuf};

/// The comment marker carried by generated shell scripts. Files outside the
/// state manifest (a wrapper in `bin_dir`, say) are still recognisable by it.
pub const MARKER: &str = "# Generated by cpx — Claude Profile Manager";

/// How far into a file the marker may appear and still count as a header.
const MARKER_SCAN_LINES: usize = 5;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Artifact {
    /// SHA-256 of the file's bytes, or of a symlink's target path.
    pub sha256: String,
    pub profile: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct State {
    #[serde(default)]
    pub artifacts: BTreeMap<PathBuf, Artifact>,
}

/// What cpx is permitted to do with an existing path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Ownership {
    /// Nothing is there.
    Absent,
    /// cpx wrote it and it is untouched.
    Ours,
    /// cpx wrote it but a human has since edited it.
    OursModified,
    /// cpx did not write it.
    Foreign,
}

pub fn sha256_bytes(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex::encode(hasher.finalize())
}

/// Hash whatever is at `path`: file contents, or a symlink's target.
///
/// Symlinks are hashed by their target path rather than followed, so a link
/// still counts as ours when what it points at changes, and a broken link is
/// still classifiable.
pub fn hash_path(path: &Path) -> io::Result<Option<String>> {
    let meta = match std::fs::symlink_metadata(path) {
        Ok(meta) => meta,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(e),
    };

    if meta.is_symlink() {
        let target = std::fs::read_link(path)?;
        return Ok(Some(sha256_bytes(target.as_os_str().as_encoded_bytes())));
    }
    if meta.is_dir() {
        return Ok(Some(String::from("dir")));
    }
    Ok(Some(sha256_bytes(&std::fs::read(path)?)))
}

/// Whether a file's first few lines carry the generated-by marker.
pub fn has_marker(path: &Path) -> bool {
    let Ok(bytes) = std::fs::read(path) else {
        return false;
    };
    let Ok(text) = std::str::from_utf8(&bytes) else {
        return false;
    };
    text.lines()
        .take(MARKER_SCAN_LINES)
        .any(|line| line.trim() == MARKER)
}

impl State {
    pub fn load(path: &Path) -> io::Result<State> {
        match std::fs::read(path) {
            Ok(bytes) => serde_json::from_slice(&bytes)
                .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e)),
            Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(State::default()),
            Err(e) => Err(e),
        }
    }

    pub fn save(&self, path: &Path) -> io::Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let text = serde_json::to_string_pretty(self)
            .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
        std::fs::write(path, text)
    }

    pub fn record(&mut self, path: &Path, sha256: String, profile: &str) {
        self.artifacts.insert(
            path.to_path_buf(),
            Artifact {
                sha256,
                profile: profile.to_string(),
            },
        );
    }

    pub fn forget(&mut self, path: &Path) {
        self.artifacts.remove(path);
    }

    /// Every artifact recorded for a profile.
    pub fn paths_for(&self, profile: &str) -> Vec<PathBuf> {
        self.artifacts
            .iter()
            .filter(|(_, a)| a.profile == profile)
            .map(|(p, _)| p.clone())
            .collect()
    }

    /// Classify what is currently at `path`.
    pub fn classify(&self, path: &Path) -> io::Result<Ownership> {
        let Some(actual) = hash_path(path)? else {
            return Ok(Ownership::Absent);
        };

        match self.artifacts.get(path) {
            Some(artifact) if artifact.sha256 == actual => Ok(Ownership::Ours),
            Some(_) => Ok(Ownership::OursModified),
            // A wrapper in bin_dir can outlive the state file — a reinstall,
            // a deleted state.json — so the marker is a second chance to
            // recognise our own work before calling it foreign.
            None if has_marker(path) => Ok(Ownership::Ours),
            None => Ok(Ownership::Foreign),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn tmp() -> TempDir {
        TempDir::new().unwrap()
    }

    #[test]
    fn hashing_is_stable_and_content_sensitive() {
        assert_eq!(sha256_bytes(b"abc"), sha256_bytes(b"abc"));
        assert_ne!(sha256_bytes(b"abc"), sha256_bytes(b"abd"));
        assert_eq!(sha256_bytes(b"abc").len(), 64);
    }

    #[test]
    fn hash_path_reports_none_for_a_missing_path() {
        let d = tmp();
        assert_eq!(hash_path(&d.path().join("nope")).unwrap(), None);
    }

    #[test]
    fn hash_path_hashes_file_contents() {
        let d = tmp();
        let f = d.path().join("f");
        fs::write(&f, b"hello").unwrap();
        assert_eq!(hash_path(&f).unwrap(), Some(sha256_bytes(b"hello")));
    }

    #[test]
    fn hash_path_hashes_a_symlink_target_not_its_destination() {
        let d = tmp();
        let target = d.path().join("target");
        fs::write(&target, b"contents").unwrap();
        let link = d.path().join("link");
        std::os::unix::fs::symlink(&target, &link).unwrap();
        assert_eq!(
            hash_path(&link).unwrap(),
            Some(sha256_bytes(target.to_str().unwrap().as_bytes()))
        );
    }

    #[test]
    fn hash_path_reports_a_broken_symlink_by_its_target() {
        let d = tmp();
        let link = d.path().join("link");
        std::os::unix::fs::symlink(d.path().join("gone"), &link).unwrap();
        assert!(hash_path(&link).unwrap().is_some());
    }

    #[test]
    fn marker_is_recognised_in_a_script_header() {
        let d = tmp();
        let f = d.path().join("wrapper");
        fs::write(&f, format!("#!/usr/bin/env bash\n{MARKER}\nexec claude\n")).unwrap();
        assert!(has_marker(&f));
    }

    #[test]
    fn marker_beyond_the_header_does_not_count() {
        let d = tmp();
        let f = d.path().join("wrapper");
        let padding = "\n".repeat(MARKER_SCAN_LINES + 2);
        fs::write(&f, format!("#!/bin/sh{padding}{MARKER}\n")).unwrap();
        assert!(!has_marker(&f));
    }

    #[test]
    fn a_file_without_the_marker_is_not_ours() {
        let d = tmp();
        let f = d.path().join("wrapper");
        fs::write(&f, "#!/bin/sh\nexec something\n").unwrap();
        assert!(!has_marker(&f));
    }

    #[test]
    fn state_round_trips_through_disk() {
        let d = tmp();
        let path = d.path().join("state.json");
        let mut state = State::default();
        state.record(Path::new("/a/b"), sha256_bytes(b"x"), "work");
        state.save(&path).unwrap();

        let loaded = State::load(&path).unwrap();
        assert_eq!(loaded.artifacts.len(), 1);
        assert_eq!(loaded.artifacts[Path::new("/a/b")].profile, "work");
    }

    #[test]
    fn loading_an_absent_state_file_yields_an_empty_state() {
        let d = tmp();
        assert!(State::load(&d.path().join("nope.json")).unwrap().artifacts.is_empty());
    }

    #[test]
    fn an_absent_path_classifies_as_absent() {
        let d = tmp();
        let state = State::default();
        assert_eq!(
            state.classify(&d.path().join("nope")).unwrap(),
            Ownership::Absent
        );
    }

    #[test]
    fn an_unrecorded_file_classifies_as_foreign() {
        let d = tmp();
        let f = d.path().join("f");
        fs::write(&f, b"hand written").unwrap();
        assert_eq!(State::default().classify(&f).unwrap(), Ownership::Foreign);
    }

    #[test]
    fn a_recorded_unchanged_file_classifies_as_ours() {
        let d = tmp();
        let f = d.path().join("f");
        fs::write(&f, b"generated").unwrap();
        let mut state = State::default();
        state.record(&f, sha256_bytes(b"generated"), "work");
        assert_eq!(state.classify(&f).unwrap(), Ownership::Ours);
    }

    #[test]
    fn a_recorded_but_edited_file_classifies_as_modified() {
        let d = tmp();
        let f = d.path().join("f");
        fs::write(&f, b"generated").unwrap();
        let mut state = State::default();
        state.record(&f, sha256_bytes(b"generated"), "work");
        fs::write(&f, b"edited by hand").unwrap();
        assert_eq!(state.classify(&f).unwrap(), Ownership::OursModified);
    }

    #[test]
    fn an_unrecorded_script_carrying_the_marker_classifies_as_ours() {
        let d = tmp();
        let f = d.path().join("claude-work");
        fs::write(&f, format!("#!/usr/bin/env bash\n{MARKER}\n")).unwrap();
        assert_eq!(State::default().classify(&f).unwrap(), Ownership::Ours);
    }

    #[test]
    fn forget_removes_an_artifact() {
        let mut state = State::default();
        state.record(Path::new("/a/b"), sha256_bytes(b"x"), "work");
        state.forget(Path::new("/a/b"));
        assert!(state.artifacts.is_empty());
    }

    #[test]
    fn paths_for_selects_only_that_profiles_artifacts() {
        let mut state = State::default();
        state.record(Path::new("/a/work"), sha256_bytes(b"x"), "work");
        state.record(Path::new("/a/personal"), sha256_bytes(b"y"), "personal");
        assert_eq!(state.paths_for("work"), vec![PathBuf::from("/a/work")]);
    }
}
