#!/usr/bin/env bash
# Cut a release: build the artifacts, publish them, and point the tap at them.
#
# Everything runs locally rather than in CI, so a release can be rehearsed and
# inspected before anything is pushed. Pass --dry-run to build and print
# without publishing.
set -euo pipefail

VERSION="${1:-}"
DRY_RUN="${2:-}"
REPO="menico/cpx"
TAP_REPO="menico/homebrew-tap"

if [[ -z "$VERSION" ]]; then
  echo "usage: scripts/release.sh <version> [--dry-run]   e.g. 0.2.0" >&2
  exit 1
fi
VERSION="${VERSION#v}"
TAG="v$VERSION"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
DIST="$ROOT/target/dist"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# The version lives in one place; everything else reads it from there.
CARGO_VERSION="$(grep -m1 '^version' Cargo.toml | cut -d'"' -f2)"
if [[ "$CARGO_VERSION" != "$VERSION" ]]; then
  echo "Cargo.toml says $CARGO_VERSION but you asked for $VERSION." >&2
  echo "Update [workspace.package] version and crates/cpx-app/tauri.conf.json first." >&2
  exit 1
fi

say "Building the CLI for both architectures"
rm -rf "$DIST"; mkdir -p "$DIST"
for target in aarch64-apple-darwin x86_64-apple-darwin; do
  cargo build --release -p cpx-cli --target "$target"
  tar -czf "$DIST/cpx-$VERSION-$target.tar.gz" -C "target/$target/release" cpx
done

# A dmg build that fails part-way leaves its scratch volume mounted, and the
# next build then fails on the name. Clear any before starting.
for volume in /Volumes/dmg.*; do
  [[ -d "$volume" ]] || continue
  echo "detaching stale $volume"
  hdiutil detach "$volume" -force >/dev/null 2>&1 || true
done

say "Building the app as a universal binary"
(cd ui && ./node_modules/.bin/vite build)
(cd crates/cpx-app && ../../ui/node_modules/.bin/tauri build --target universal-apple-darwin)
APP="target/universal-apple-darwin/release/bundle/macos/cpx.app"
codesign --force --deep --sign - "$APP"
DMG="$(ls target/universal-apple-darwin/release/bundle/dmg/*.dmg | head -1)"
cp "$DMG" "$DIST/cpx-$VERSION-universal.dmg"

say "Checksums"
(cd "$DIST" && shasum -a 256 * | tee checksums.txt)

sha_of() { shasum -a 256 "$DIST/$1" | cut -d' ' -f1; }
SHA_ARM="$(sha_of "cpx-$VERSION-aarch64-apple-darwin.tar.gz")"
SHA_X86="$(sha_of "cpx-$VERSION-x86_64-apple-darwin.tar.gz")"
SHA_DMG="$(sha_of "cpx-$VERSION-universal.dmg")"

if [[ "$DRY_RUN" == "--dry-run" ]]; then
  say "Dry run — built in $DIST, nothing published"
  exit 0
fi

say "Publishing $TAG to $REPO"
git tag -f "$TAG"
git push origin "$TAG" --force
gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1 \
  && gh release delete "$TAG" --repo "$REPO" --yes
gh release create "$TAG" --repo "$REPO" --title "$TAG" \
  --notes "Install: \`brew tap menico/tap && brew install cpx\`" \
  "$DIST/cpx-$VERSION-aarch64-apple-darwin.tar.gz" \
  "$DIST/cpx-$VERSION-x86_64-apple-darwin.tar.gz" \
  "$DIST/cpx-$VERSION-universal.dmg"

say "Pointing the tap at $TAG"
TAP="$(mktemp -d)"
gh repo clone "$TAP_REPO" "$TAP" -- --quiet
mkdir -p "$TAP/Formula" "$TAP/Casks"

cat > "$TAP/Formula/cpx.rb" <<FORMULA
# Generated by scripts/release.sh — edit that, not this.
class Cpx < Formula
  desc "Run several Claude Code accounts side by side"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/$REPO/releases/download/$TAG/cpx-$VERSION-aarch64-apple-darwin.tar.gz"
      sha256 "$SHA_ARM"
    end
    on_intel do
      url "https://github.com/$REPO/releases/download/$TAG/cpx-$VERSION-x86_64-apple-darwin.tar.gz"
      sha256 "$SHA_X86"
    end
  end

  def install
    bin.install "cpx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cpx --version")
  end
end
FORMULA

cat > "$TAP/Casks/cpx.rb" <<CASK
# Generated by scripts/release.sh — edit that, not this.
cask "cpx" do
  version "$VERSION"
  sha256 "$SHA_DMG"

  url "https://github.com/$REPO/releases/download/v#{version}/cpx-#{version}-universal.dmg"
  name "cpx"
  desc "Menu-bar app for managing Claude Code profiles"
  homepage "https://github.com/$REPO"

  app "cpx.app"

  # The app is ad-hoc signed rather than notarised, so macOS quarantines it
  # on download. Removing the flag here saves a right-click-open.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/cpx.app"],
                   sudo: false
  end

  # Deliberately does not list ~/.claude-profiles. Profiles hold real state
  # — session history for anything in `own` mode, and adopted directories are
  # the user's own working directories. Uninstalling the app must not take
  # them; `cpx` can remove a profile deliberately.
  zap trash: [
    "~/Library/Application Support/io.github.menico.cpx",
  ]
end
CASK

git -C "$TAP" add -A
git -C "$TAP" commit -q -m "cpx $VERSION" || { echo "tap already up to date"; }
git -C "$TAP" push -q
rm -rf "$TAP"

say "Released $TAG"
echo
echo "  brew tap menico/tap"
echo "  brew install cpx          # the command"
echo "  brew install --cask cpx   # the menu-bar app"
echo
echo "To update later:  brew update && brew upgrade cpx"
